// <auto-generated />
namespace Super_Zapatos_Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class StoresArticles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StoresArticles));
        
        string IMigrationMetadata.Id
        {
            get { return "202102052226455_Stores-Articles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
